apiVersion: apps/v1
kind: Deployment
metadata:
  name: "todo"
spec:
  selector:
    matchLabels:
      app: "todo"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "todo"
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: "todo"
        ports:
        - containerPort: 80